name = "bingqilin-links"
main = "src/worker.js"
compatibility_date = "2024-09-23"

[assets]
directory = "./public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "LINKS"
id = "REPLACE_WITH_YOUR_KV_NAMESPACE_ID"
